-- CreateTable
CREATE TABLE "cr5c7_importbatch" (
    "cr5c7_ImportBatchId" TEXT NOT NULL PRIMARY KEY,
    "cr5c7_BatchName" TEXT,
    "cr5c7_CurrentTotal" DECIMAL,
    "cr5c7_currenttotal_Base" DECIMAL,
    "cr5c7_FileName" TEXT,
    "cr5c7_ImportDate" DATETIME,
    "cr5c7_ImportMonth" INTEGER,
    "cr5c7_ImportYear" INTEGER,
    "cr5c7_LastTotal" DECIMAL,
    "cr5c7_lasttotal_Base" DECIMAL,
    "cr5c7_Status" INTEGER,
    "cr5c7_Variance" DECIMAL,
    "cr5c7_variance_Base" DECIMAL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ExchangeRate" DECIMAL,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "TransactionCurrencyId" TEXT,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "cr5c7_monthlyrevenue" (
    "cr5c7_MonthlyRevenueId" TEXT NOT NULL PRIMARY KEY,
    "cr5c7_MonthlyRevenueName" TEXT,
    "cr5c7_Amount" DECIMAL,
    "cr5c7_amount_Base" DECIMAL,
    "cr5c7_Batch" TEXT NOT NULL,
    "cr5c7_IsEstimated" BOOLEAN,
    "cr5c7_Locked" BOOLEAN,
    "cr5c7_Month" INTEGER NOT NULL,
    "cr5c7_Project" TEXT NOT NULL,
    "cr5c7_Type" INTEGER,
    "cr5c7_Year" INTEGER NOT NULL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ExchangeRate" DECIMAL,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "TransactionCurrencyId" TEXT,
    "UTCConversionTimeZoneCode" INTEGER,
    CONSTRAINT "cr5c7_monthlyrevenue_cr5c7_Batch_fkey" FOREIGN KEY ("cr5c7_Batch") REFERENCES "cr5c7_importbatch" ("cr5c7_ImportBatchId") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "cr5c7_monthlyrevenue_cr5c7_Project_fkey" FOREIGN KEY ("cr5c7_Project") REFERENCES "cr5c7_projectmaster" ("cr5c7_ProjectMasterId") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "cr5c7_projectmaster" (
    "cr5c7_ProjectMasterId" TEXT NOT NULL PRIMARY KEY,
    "cr5c7_BusinessUnitDescription" TEXT,
    "cr5c7_Category" TEXT,
    "cr5c7_CustomerDescription" TEXT,
    "cr5c7_CustomerID" TEXT,
    "cr5c7_EDLID" TEXT,
    "cr5c7_EDLName" TEXT,
    "cr5c7_JanPPM" TEXT,
    "cr5c7_MarketsDescription" TEXT,
    "cr5c7_MarketUnitDescription" TEXT,
    "cr5c7_OpportunityID" TEXT,
    "cr5c7_OpportunityName" TEXT,
    "cr5c7_ParentCustomer" TEXT,
    "cr5c7_PDLID" TEXT,
    "cr5c7_PDLName" TEXT,
    "cr5c7_PMID" TEXT,
    "cr5c7_PMName" TEXT,
    "cr5c7_ProjectBillability" TEXT,
    "cr5c7_ProjectDescription" TEXT,
    "cr5c7_ProjectEndDate" DATETIME NOT NULL,
    "cr5c7_SOID" TEXT,
    "cr5c7_SubPracticeDesc" TEXT,
    "cr5c7_Tower" TEXT,
    "cr5c7_VerticalDescription" TEXT,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "cr5c7_submissionsummary" (
    "cr5c7_SubmissionSummaryId" TEXT NOT NULL PRIMARY KEY,
    "cr5c7_SubmissionSummaryName" TEXT,
    "cr5c7_Batch" TEXT NOT NULL,
    "cr5c7_CurrentTotal" DECIMAL,
    "cr5c7_currenttotal_Base" DECIMAL,
    "cr5c7_LastTotal" DECIMAL,
    "cr5c7_lasttotal_Base" DECIMAL,
    "cr5c7_Project" TEXT NOT NULL,
    "cr5c7_Trend" INTEGER,
    "cr5c7_Variance" DECIMAL,
    "cr5c7_variance_Base" DECIMAL,
    "cr5c7_Variance1" DECIMAL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ExchangeRate" DECIMAL,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "TransactionCurrencyId" TEXT,
    "UTCConversionTimeZoneCode" INTEGER,
    CONSTRAINT "cr5c7_submissionsummary_cr5c7_Batch_fkey" FOREIGN KEY ("cr5c7_Batch") REFERENCES "cr5c7_importbatch" ("cr5c7_ImportBatchId") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "cr5c7_submissionsummary_cr5c7_Project_fkey" FOREIGN KEY ("cr5c7_Project") REFERENCES "cr5c7_projectmaster" ("cr5c7_ProjectMasterId") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "mbg_customer1" (
    "mbg_Customer1Id" TEXT NOT NULL PRIMARY KEY,
    "mbg_CustomerName" TEXT NOT NULL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "mbg_opportunity1" (
    "mbg_Opportunity1Id" TEXT NOT NULL PRIMARY KEY,
    "mbg_OpportunityName" TEXT NOT NULL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "mbg_salesorder" (
    "mbg_SalesOrderId" TEXT NOT NULL PRIMARY KEY,
    "mbg_SalesOrderNumber" TEXT NOT NULL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "mbg_submission" (
    "mbg_SubmissionId" TEXT NOT NULL PRIMARY KEY,
    "mbg_SubmissionName" TEXT NOT NULL,
    "mbg_FinancialYear" TEXT NOT NULL,
    "mbg_Project" TEXT NOT NULL,
    "mbg_Status" INTEGER NOT NULL,
    "mbg_SubmissionDate" DATETIME,
    "mbg_SubmittedBy" TEXT,
    "mbg_TotalValue" DECIMAL,
    "mbg_totalvalue_Base" DECIMAL,
    "mbg_Type" INTEGER NOT NULL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ExchangeRate" DECIMAL,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "TransactionCurrencyId" TEXT,
    "UTCConversionTimeZoneCode" INTEGER,
    CONSTRAINT "mbg_submission_mbg_SubmittedBy_fkey" FOREIGN KEY ("mbg_SubmittedBy") REFERENCES "mbg_resourceperson" ("mbg_ResourcePersonId") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "mbg_revenuerecord" (
    "mbg_RevenueRecordId" TEXT NOT NULL PRIMARY KEY,
    "mbg_ActualAmount" DECIMAL,
    "mbg_actualamount_Base" DECIMAL,
    "mbg_CurrentSubmissionAmount" DECIMAL,
    "mbg_currentsubmissionamount_Base" DECIMAL,
    "mbg_FinancialYear" TEXT NOT NULL,
    "mbg_ForecastAmount" DECIMAL,
    "mbg_forecastamount_Base" DECIMAL,
    "mbg_IsAutoEstimated" BOOLEAN,
    "mbg_IsLocked" BOOLEAN,
    "mbg_LastSubmissionAmount" DECIMAL,
    "mbg_lastsubmissionamount_Base" DECIMAL,
    "mbg_MonthName" TEXT NOT NULL,
    "mbg_MonthNumber" INTEGER NOT NULL,
    "mbg_Project" TEXT NOT NULL,
    "mbg_Reason" TEXT,
    "mbg_VarianceAmount" DECIMAL,
    "mbg_varianceamount_Base" DECIMAL,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ExchangeRate" DECIMAL,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "TransactionCurrencyId" TEXT,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "mbg_orgstructure" (
    "mbg_OrgStructureId" TEXT NOT NULL PRIMARY KEY,
    "mbg_BU" TEXT,
    "mbg_Category" TEXT,
    "mbg_Market" TEXT,
    "mbg_OrgStructureName" TEXT NOT NULL,
    "mbg_SubPractice" TEXT,
    "mbg_Tower" TEXT,
    "mbg_Vertical" TEXT,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "UTCConversionTimeZoneCode" INTEGER
);

-- CreateTable
CREATE TABLE "mbg_resourceperson" (
    "mbg_ResourcePersonId" TEXT NOT NULL PRIMARY KEY,
    "mbg_Email" TEXT,
    "mbg_FullName" TEXT NOT NULL,
    "mbg_Phone" TEXT,
    "CreatedBy" TEXT,
    "CreatedOn" DATETIME,
    "CreatedOnBehalfBy" TEXT,
    "ImportSequenceNumber" INTEGER,
    "ModifiedBy" TEXT,
    "ModifiedOn" DATETIME,
    "ModifiedOnBehalfBy" TEXT,
    "OverriddenCreatedOn" DATETIME,
    "OwnerId" TEXT NOT NULL,
    "OwningBusinessUnit" TEXT,
    "OwningTeam" TEXT,
    "OwningUser" TEXT,
    "statecode" INTEGER NOT NULL,
    "statuscode" INTEGER,
    "TimeZoneRuleVersionNumber" INTEGER,
    "UTCConversionTimeZoneCode" INTEGER
);
